[[accounts]]
email  = "first@example.com"
name   = "First Account"
host   = "imap.first.example"
port   = 993
secure = true
user   = "first@example.com"

[[accounts]]
email  = "second@example.com"
name   = "Second Account"
host   = "imap.second.example"
port   = 993
secure = true
user   = "second@example.com"
